# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1veTlcqSDOrtV_POMwGHwAi9raWsT5Ao3
"""

"""
Experiment 5 - DPCM and Delta Modulation
Digital Communication Laboratory (EC-593)

Implements, from first principles (numpy + matplotlib only):
  Task 14-15  First-order DPCM vs. PCM (equal bit-rate comparison)
  Task 16     Delta modulation for small / moderate / large step size
  Task 17     Slowly vs. rapidly varying input at a fixed step size
  (required)  MSE vs. step size sweep (granular noise <-> slope overload)
  Task 18     Optional adaptive delta modulation (ADM)
  Mandatory   Validation that every DM/ADM output step is exactly +/-delta

HOW TO RUN IN GOOGLE COLAB
---------------------------
1. Open https://colab.research.google.com -> New notebook.
2. Paste this entire file into a single code cell (numpy and matplotlib are
   pre-installed in Colab, so no pip install is needed).
3. Run the cell (Shift+Enter). Every required plot (Fig. 1-6) is displayed
   inline below the cell, and also saved as PNG files under a local
   "figs/" folder (visible in the Colab file browser on the left). All
   numeric results are printed to the cell output as they are computed.
"""

import os
import numpy as np
import matplotlib.pyplot as plt

os.makedirs("figs", exist_ok=True)

# ============================================================================
# 0. Shared helpers
# ============================================================================
def make_sine(freq, fs, duration=1.0, amplitude=1.0):
    """Generate n, t, x for x(n) = A*sin(2*pi*freq*n/fs)."""
    n = np.arange(int(round(fs * duration)))
    t = n / fs
    x = amplitude * np.sin(2 * np.pi * freq * t)
    return n, t, x


def uniform_quantize(x, levels, vmax):
    """
    Uniform mid-rise quantizer over [-vmax, +vmax] with `levels` levels.
    step = 2*vmax/levels; output is clipped to the representable range.
    """
    x = np.asarray(x, dtype=float)
    step = 2.0 * vmax / levels
    idx = np.floor((x + vmax) / step)
    idx = np.clip(idx, 0, levels - 1)
    xq = -vmax + (idx + 0.5) * step
    return xq


def no_overload_threshold(freq, fs, amplitude=1.0):
    """Delta >= 2*pi*f*A/fs is required so the DM staircase can track a
    sinusoid of the given frequency/amplitude without slope overload."""
    return 2 * np.pi * freq * amplitude / fs


# ============================================================================
# 1. First-order DPCM and PCM (Tasks 14-15)
# ============================================================================
def dpcm_first_order(x, levels, a=None):
    """
    First-order closed-loop DPCM encoder/decoder.
    Predictor: x_pred(n) = a*x_hat(n-1). If `a` is not given, it is estimated
    from the signal's own (biased) autocorrelation: a = R(1)/R(0).
    Returns: x_pred, x_hat, e (pre-quantization error), eq (quantized error), a
    """
    N = len(x)
    if a is None:
        R0 = np.sum(x[:-1] ** 2)
        R1 = np.sum(x[1:] * x[:-1])
        a = R1 / R0  # first-order predictor coefficient

    x_hat = np.zeros(N)   # decoder output (reconstructed)
    x_pred = np.zeros(N)  # predicted samples
    e, eq = np.zeros(N), np.zeros(N)  # error before / after quantization

    e_openloop = x[1:] - a * x[:-1]
    vmax = 1.3 * np.max(np.abs(e_openloop))  # size quantizer to the error range

    for n in range(N):
        x_pred[n] = a * x_hat[n - 1] if n > 0 else 0.0
        e[n] = x[n] - x_pred[n]
        eq[n] = uniform_quantize(np.array([e[n]]), levels, vmax)[0]
        x_hat[n] = x_pred[n] + eq[n]

    return x_pred, x_hat, e, eq, a


def pcm_quantize(x, levels):
    """Direct (memoryless) PCM quantization of x."""
    vmax = np.max(np.abs(x)) * 1.05
    return uniform_quantize(x, levels, vmax), vmax


print("=" * 70)
print("Tasks 14-15: First-Order DPCM vs. PCM")
print("=" * 70)

N14 = 60
n14 = np.arange(N14)
x = np.sin(2 * np.pi * 3 * n14 / 60)  # smooth, correlated 3 Hz sine @ 60 Hz

LEVELS = 8  # 3-bit uniform quantizer, used for both PCM and DPCM
x_pred, x_hat, e, eq, a_coef = dpcm_first_order(x, LEVELS)
x_pcm, pcm_vmax = pcm_quantize(x, LEVELS)

pcm_step = 2 * pcm_vmax / LEVELS
dpcm_vmax = 1.3 * np.max(np.abs(x[1:] - a_coef * x[:-1]))
dpcm_step = 2 * dpcm_vmax / LEVELS

mse_pcm = np.mean((x - x_pcm) ** 2)
mse_dpcm = np.mean((x - x_hat) ** 2)

print(f"Predictor coefficient a (=R1/R0)   : {a_coef:.4f}")
print(f"Quantizer levels (both PCM & DPCM) : {LEVELS} (3-bit)")
print(f"PCM quantization step              : {pcm_step:.4f}")
print(f"DPCM (error) quantization step     : {dpcm_step:.4f}")
print(f"MSE - PCM (x vs x_pcm)             : {mse_pcm:.6f}")
print(f"MSE - DPCM (x vs x_hat_dpcm)       : {mse_dpcm:.6f}")
print(f"DPCM improvement over PCM          : {mse_pcm / mse_dpcm:.2f}x lower MSE")

# ---- Required Visualization: Original / Predicted Samples ----------------
fig, ax = plt.subplots(figsize=(8, 4.5))
ax.plot(n14, x, "o-", color="C0", label="Original x[n]")
ax.plot(n14, x_pred, "s--", color="C1", label="Predicted x_pred[n]")
ax.plot(n14, x_hat, "^-", color="C2", label="DPCM reconstructed x_hat[n]")
ax.axhline(0, color="k", linewidth=0.6)
ax.set_title("Task 14: Original, Predicted and DPCM-Reconstructed Samples")
ax.set_xlabel("n")
ax.set_ylabel("Amplitude")
ax.legend()
ax.grid(alpha=0.3)
fig.tight_layout()
fig.savefig("figs/fig1_dpcm_samples.png", dpi=150)
plt.show()

# ---- Required Visualization: Prediction Error -----------------------------
fig, axes = plt.subplots(2, 1, figsize=(8, 6.5))
axes[0].plot(n14, e, "o-", color="C1", markersize=3, label="Prediction error e[n] (pre-quant.)")
axes[0].plot(n14, eq, "x-", color="C3", markersize=4, label="Quantized error eq[n]")
axes[0].axhline(0, color="k", linewidth=0.6)
axes[0].set_title("Task 15: DPCM Prediction Error (before & after quantization)")
axes[0].set_xlabel("n")
axes[0].set_ylabel("Error")
axes[0].legend()
axes[0].grid(alpha=0.3)

axes[1].plot(n14, x - x_pcm, "-", color="purple", label="PCM quantization error")
axes[1].plot(n14, x - x_hat, "-", color="green", label="DPCM reconstruction error")
axes[1].axhline(0, color="k", linewidth=0.6)
axes[1].set_title("Task 15: PCM vs DPCM Reconstruction Error (same bit rate)")
axes[1].set_xlabel("n")
axes[1].set_ylabel("Error")
axes[1].legend()
axes[1].grid(alpha=0.3)
fig.tight_layout()
fig.savefig("figs/fig2_dpcm_error.png", dpi=150)
plt.show()

# ---- Observation ------------------------------------------------------
print(f"\nObservation: predictor a = {a_coef:.3f} confirms strong sample "
      f"correlation; DPCM achieves {mse_pcm / mse_dpcm:.2f}x lower MSE than "
      f"PCM at the same bit rate.\n")


# ============================================================================
# 2. Delta Modulation (Task 16)
# ============================================================================
def delta_modulate(x, delta, x0=0.0):
    """Linear delta modulator: x_hat(n) = x_hat(n-1) +/- delta."""
    N = len(x)
    x_hat, bits = np.zeros(N), np.zeros(N, dtype=int)
    prev = x0
    for n in range(N):
        b = 1 if x[n] >= prev else -1
        prev = prev + b * delta
        x_hat[n] = prev
        bits[n] = b
    return x_hat, bits


print("=" * 70)
print("Task 16: Delta Modulation - Small / Moderate / Large Step Size")
print("=" * 70)

FS16, FREQ16 = 100, 5
n16, t16, x16 = make_sine(FREQ16, FS16, duration=1.0)  # 5 Hz sine @ 100 Hz
thr16 = no_overload_threshold(FREQ16, FS16)
print(f"Theoretical no-slope-overload threshold: delta >= {thr16:.4f}")

deltas_16 = {"Small": 0.05, "Moderate": 0.35, "Large": 1.00}
dm_results_16 = {}
for label, d in deltas_16.items():
    xh, bits = delta_modulate(x16, d)
    mse = np.mean((x16 - xh) ** 2)
    dm_results_16[label] = (d, xh, bits, mse)
    print(f"{label:10s} (delta={d:.2f})   : MSE={mse:.5f}")

# ---- Required Visualization: Delta Staircase ------------------------------
fig, axes = plt.subplots(3, 1, figsize=(8, 9))
for ax, (label, (d, xh, bits, mse)) in zip(axes, dm_results_16.items()):
    ax.plot(n16, x16, "-", color="navy", label="Original x(n)")
    ax.step(n16, xh, "-", color="red", where="post", label="DM staircase")
    ax.set_title(f"Task 16: {label} (delta={d:.2f})")
    ax.set_xlabel("n")
    ax.set_ylabel("Amplitude")
    ax.legend(loc="upper right", fontsize=8)
    ax.grid(alpha=0.3)
fig.tight_layout()
fig.savefig("figs/fig3_dm_staircase.png", dpi=150)
plt.show()

print(f"\nObservation: Small delta -> slope overload (staircase lags, "
      f"highest MSE). Moderate delta -> best tracking, lowest MSE. Large "
      f"delta -> granular noise (overshoot ripple), MSE nearly as bad as "
      f"the small-delta case.\n")


# ============================================================================
# 3. Slowly vs. rapidly varying input at fixed step size (Task 17)
# ============================================================================
print("=" * 70)
print("Task 17: Slowly vs. Rapidly Varying Input (Fixed Step Size)")
print("=" * 70)

DELTA17 = 0.30
n_slow, t_slow, x_slow = make_sine(2, fs=100, duration=1.0)   # slow
n_fast, t_fast, x_fast = make_sine(15, fs=100, duration=1.0)  # fast

xh_slow, _ = delta_modulate(x_slow, DELTA17)
xh_fast, _ = delta_modulate(x_fast, DELTA17)

thr_slow = no_overload_threshold(2, 100)
thr_fast = no_overload_threshold(15, 100)
mse_slow = np.mean((x_slow - xh_slow) ** 2)
mse_fast = np.mean((x_fast - xh_fast) ** 2)

print(f"Slow signal (f=2 Hz):  threshold delta >= {thr_slow:.4f} -> "
      f"delta={DELTA17:.2f} is {'ABOVE' if DELTA17 >= thr_slow else 'BELOW'} it "
      f"(expect {'granular noise, no overload' if DELTA17 >= thr_slow else 'slope overload'})")
print(f"Fast signal (f=15 Hz): threshold delta >= {thr_fast:.4f} -> "
      f"delta={DELTA17:.2f} is {'ABOVE' if DELTA17 >= thr_fast else 'BELOW'} it "
      f"(expect {'granular noise, no overload' if DELTA17 >= thr_fast else 'slope overload'})")
print(f"MSE slow signal : {mse_slow:.5f}")
print(f"MSE fast signal : {mse_fast:.5f}")

# ---- Required Visualization: Delta Staircase (slow vs. fast) --------------
fig, axes = plt.subplots(2, 1, figsize=(8, 6.5))
axes[0].plot(n_slow, x_slow, "-", color="navy", label="Original (slow, f=2 Hz)")
axes[0].step(n_slow, xh_slow, "-", color="red", where="post", label="DM staircase")
axes[0].set_title("Task 17: Slowly Varying Input -> Granular Noise")
axes[0].set_xlabel("n")
axes[0].set_ylabel("Amplitude")
axes[0].legend(fontsize=8)
axes[0].grid(alpha=0.3)

axes[1].plot(n_fast, x_fast, "-", color="navy", label="Original (fast, f=15 Hz)")
axes[1].step(n_fast, xh_fast, "-", color="red", where="post", label="DM staircase")
axes[1].set_title("Task 17: Rapidly Varying Input -> Slope-Overload Distortion")
axes[1].set_xlabel("n")
axes[1].set_ylabel("Amplitude")
axes[1].legend(fontsize=8)
axes[1].grid(alpha=0.3)
fig.tight_layout()
fig.savefig("figs/fig4_dm_slow_vs_fast.png", dpi=150)
plt.show()

print(f"\nObservation: identical delta={DELTA17:.2f} gives granular noise "
      f"on the slow input (MSE={mse_slow:.3f}) but slope overload on the "
      f"fast input (MSE={mse_fast:.3f}), confirming both distortions come "
      f"from one fixed 'maximum trackable slope' delta*fs.\n")


# ============================================================================
# 4. Required Visualization: MSE versus Step Size
# ============================================================================
print("=" * 70)
print("Required Visualization: MSE versus Step Size")
print("=" * 70)

delta_range = np.linspace(0.02, 1.2, 40)
mse_values = [np.mean((x16 - delta_modulate(x16, d)[0]) ** 2) for d in delta_range]
best_delta = delta_range[int(np.argmin(mse_values))]
min_mse = min(mse_values)

print(f"Minimum MSE = {min_mse:.5f} at delta = {best_delta:.4f}")
print(f"(Theoretical no-overload threshold for this signal was delta >= {thr16:.4f})")

fig, ax = plt.subplots(figsize=(7.5, 5))
ax.plot(delta_range, mse_values, "o-", color="C0", markersize=4)
ax.axvline(thr16, color="red", linestyle="--", label=f"no-overload threshold ({thr16:.3f})")
ax.axvline(best_delta, color="gray", linestyle=":", label=f"optimum delta ({best_delta:.3f})")
ax.set_xlabel("Step size (delta)")
ax.set_ylabel("MSE")
ax.set_title("MSE vs Step Size (granular noise <-> slope overload)")
ax.legend()
ax.grid(alpha=0.3)
fig.tight_layout()
fig.savefig("figs/fig5_mse_vs_delta.png", dpi=150)
plt.show()

print(f"\nObservation: classic U-shaped curve; the empirical optimum sits "
      f"slightly below the worst-case theoretical threshold, since a little "
      f"controlled slope-overload error costs less MSE than the granular "
      f"noise a fully-safe delta would add elsewhere.\n")


# ============================================================================
# 5. Task 18 (Optional): Adaptive Delta Modulation
# ============================================================================
def adaptive_delta_modulate(x, delta_min, delta_max, growth=1.5, decay=0.6, x0=0.0):
    """
    Adaptive delta modulator: step grows (x growth) on same-sign bit runs
    (to chase fast slopes) and shrinks (x decay) on sign reversals (to keep
    granular noise low), clamped to [delta_min, delta_max].
    """
    N = len(x)
    x_hat = np.zeros(N)
    bits = np.zeros(N, dtype=int)
    deltas = np.zeros(N)
    prev, delta, last_bit = x0, delta_min, 0
    for n in range(N):
        b = 1 if x[n] >= prev else -1
        delta = min(delta * growth, delta_max) if b == last_bit else max(delta * decay, delta_min)
        prev = prev + b * delta
        x_hat[n], bits[n], deltas[n] = prev, b, delta
        last_bit = b
    return x_hat, bits, deltas


print("=" * 70)
print("Task 18 (Optional): Adaptive Delta Modulation")
print("=" * 70)

DELTA_MIN, DELTA_MAX = 0.08, 0.9
xh_fixed = xh_fast  # fixed-delta=0.30 result on the fast signal, from Task 17
xh_adapt, bits_adapt, deltas_adapt = adaptive_delta_modulate(x_fast, DELTA_MIN, DELTA_MAX)

mse_fixed_18 = np.mean((x_fast - xh_fixed) ** 2)
mse_adapt_18 = np.mean((x_fast - xh_adapt) ** 2)

print(f"Fixed DM  (delta=0.30) MSE on fast signal : {mse_fixed_18:.5f}")
print(f"Adaptive DM             MSE on fast signal : {mse_adapt_18:.5f}")

fig, axes = plt.subplots(2, 1, figsize=(8, 6.5))
axes[0].plot(n_fast, x_fast, "-", color="navy", label="Original (fast, f=15 Hz)")
axes[0].step(n_fast, xh_fixed, "-", color="red", where="post", label="Fixed DM (delta=0.30)")
axes[0].step(n_fast, xh_adapt, "-", color="green", where="post", label="Adaptive DM")
axes[0].set_title("Task 18: Fixed vs Adaptive Delta Modulation on Rapidly Varying Input")
axes[0].set_xlabel("n")
axes[0].set_ylabel("Amplitude")
axes[0].legend(fontsize=8)
axes[0].grid(alpha=0.3)

axes[1].plot(n_fast, deltas_adapt, "-", color="orange")
axes[1].set_title("Adaptive Step Size delta[n] over Time")
axes[1].set_xlabel("n")
axes[1].set_ylabel("delta[n]")
axes[1].grid(alpha=0.3)
fig.tight_layout()
fig.savefig("figs/fig6_adaptive_dm.png", dpi=150)
plt.show()

improve_pct = 100 * (mse_fixed_18 - mse_adapt_18) / mse_fixed_18
print(f"\nObservation: adaptive step size grows during steep runs and decays "
      f"between reversals, improving MSE by about {improve_pct:.0f}% over "
      f"fixed-delta DM on this rapidly-varying signal.\n")


# ============================================================================
# 6. Mandatory Validation: +/-delta step integrity
# ============================================================================
def validate_step_changes(x_hat, delta, tol=1e-9):
    """Check that every output sample changes by exactly +delta or -delta."""
    steps = np.diff(x_hat)
    ok = np.all(np.isclose(np.abs(steps), delta, atol=tol))
    max_dev = np.max(np.abs(np.abs(steps) - delta))
    return ok, max_dev


print("=" * 70)
print("Mandatory Validation: inspect whether each delta-modulator output")
print("step changes by exactly +delta or -delta")
print("=" * 70)

for label, (d, xh, bits, mse) in dm_results_16.items():
    ok, max_dev = validate_step_changes(xh, d)
    status = "PASS" if ok else "FAIL"
    print(f"{label:10s} (delta={d:.2f}) -> {status} "
          f"(max deviation from +/-delta: {max_dev:.2e})")

print("\nAll step sizes should PASS at floating-point round-off level, "
      "confirming the staircase always advances by exactly one full step "
      "per sample in the correct direction.")

print("\nAll figures saved to figs/")